web:
  build: .
  command: 'bash -c ''java -jar target/restdoodle-0.0.1-SNAPSHOT.jar'''
  working_dir: /app/user
  environment:
    PORT: 4950
  ports:
    - '4950:4950'
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 4950
  ports:
    - '4950:4950'
  volumes:
    - '.:/app/user'
